### ISSUE TITLE
How to read roaringbitmap  from database,such as greenplum ?

### ISSUE THREAD

**Issue by sydt2014** [RoaringBitmap/RoaringBitmap#318] opened 2019-03-07 09:00 UTC
I create roaringbitmap data in greenplum, but how to read these data by JDBC in java and create roaringbitmap object ?And how to write roaringbitmap into database ,such as greenplum?

**Comment by lemire** [comment] 2019-03-07 14:15
You can, for example, store an array of bytes in your database... You’ll find plenty of examples online...

https://stackoverflow.com/questions/15134357/storing-a-byte-array-in-ms-sql

**Comment by lemire** [comment] 2019-03-07 14:17
Then serialize and deserialize bitmaps to byte arrays, see this example...

https://github.com/RoaringBitmap/RoaringBitmap/blob/master/examples/SerializeToByteArrayExample.java

**Comment by lemire** [comment] 2019-03-07 14:18
If you need support specifically with greenplum please see the greenplum developers.

**Comment by lemire** [comment] 2019-03-07 14:19
Closing. The author of the issue is encouraged to go seek support with greenplum https://greenplum.org

**Closed** 2019-03-07 14:20 UTC

**Comment by sydt2014** [comment] 2019-03-11 08:08
thanks your advise very much!
