### ISSUE TITLE
Support for the Java module system?

### ISSUE THREAD

**Issue by matteo-catena** [RoaringBitmap/RoaringBitmap#651] opened 2023-09-01 08:42 UTC
Hello everyone. My team is considering using RoaringBitmap in our product (a plugin for elasticsearch) but we are encountering some issue at runtime, which I believe is related to the java module system that elasticsearch adopts. I wonder if to modularize RoaringBitmap would help with this.

```
java.lang.module.ResolutionException: Modules shims and RoaringBitmap export package org.roaringbitmap to module java.uuid.generator
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:900)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:814)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:735)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:139)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:493)
	at org.elasticsearch.server@8.7.1/org.elasticsearch.plugins.PluginsService.createModuleLayer(PluginsService.java:705)
	at org.elasticsearch.server@8.7.1/org.elasticsearch.plugins.PluginsService.createPluginModuleLayer(PluginsService.java:673)
	at org.elasticsearch.server@8.7.1/org.elasticsearch.plugins.PluginsService.createPlugin(PluginsService.java:527)
	at org.elasticsearch.server@8.7.1/org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.java:451)
	at org.elasticsearch.server@8.7.1/org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:292)
	at org.elasticsearch.server@8.7.1/org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:161)
	at org.elasticsearch.server@8.7.1/org.elasticsearch.plugins.PluginsService.lambda$getPluginsServiceCtor$15(PluginsService.java:668)
	at org.elasticsearch.server@8.7.1/org.elasticsearch.node.Node.<init>(Node.java:417)
	at org.elasticsearch.server@8.7.1/org.elasticsearch.node.Node.<init>(Node.java:324)
	at org.elasticsearch.server@8.7.1/org.elasticsearch.bootstrap.Elasticsearch$2.<init>(Elasticsearch.java:216)
	at org.elasticsearch.server@8.7.1/org.elasticsearch.bootstrap.Elasticsearch.initPhase3(Elasticsearch.java:216)
	at org.elasticsearch.server@8.7.1/org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67)
```

For what it matters, the issue my team encountered seems similar to the one reported in [this stackoverflow question](https://stackoverflow.com/questions/71288102/java-11-gradle-with-modules-javafx-tablesaw-yields-resolutionexception).

Thanks for your attention,
Matteo

**Comment by lemire** [comment] 2023-09-01 13:58
Pull request invited.

**Comment by novoj** [comment] 2023-09-20 19:18
I've made a pull request: https://github.com/RoaringBitmap/RoaringBitmap/pull/656

I'm afraid you'll reject the PR, because I had to get rid of the `shims` module and upgrade the base java from `8` to `11` to get the `module-info.java` to work. There may be a way to make this work, but it's beyond my ability to tame the Java module system.

On the other hand - Java 11 is more than 1 year EOL: https://endoflife.date/java ... isn't it a good time to drop its support in RoaringBitmaps? ;)

**Comment by novoj** [comment] 2023-09-20 19:42
On the other hand, 33% are still running Java 8 :/ ... according to this presentation: https://docs.google.com/presentation/d/1oMDMQrTiHNkkyL9PnE9A-jLcJBD-ljNwg_JhzvjdzzA/edit#slide=id.g27e04a1c42f_0_0

The figures were taken from: https://newrelic.com/resources/report/2023-state-of-the-java-ecosystem#most-used-java-versions

I'm shooting myself in my own foot, but it's fair to talk about objective numbers.

**Comment by lemire** [comment] 2023-09-20 23:10
@richardstartin Can you comment? What do you think?

Speaking for myself, I am ok with dropping JDK8 support going forward.

**Comment by lemire** [comment] 2023-09-21 04:20
This tweet suggests modules are not actually beneficial or use in production:
https://twitter.com/nevgeniev/status/1704686184302063746?s=46&t=-zo9kVFDyKuN4X1cdtkIrw

**Comment by lemire** [comment] 2023-09-21 04:22
I am also getting a lot of feedback against dropping JDK8.

So I think we will need to keep JDK 8 support.

If modules break JDK 8 support, maybe the problem is with modules themselves?

**Comment by stiemannkj1** [comment] 2023-09-21 05:21
Added a PR here which adds `module-info.java` without dropping Java 8 support: https://github.com/RoaringBitmap/RoaringBitmap/pull/657

**Comment by novoj** [comment] 2023-09-21 05:54
It wouldn't be such a problem not to have modular support in RoaringBitmaps, since the Java module systems can work around this using "automatic modules" (see https://dev.java/learn/modules/automatic-module/). The problem is with the `shim` JAR, which is a separate JAR but uses the same package as the `RoaringBitmap` JAR. In the Java 9 module system, JARs have to declare different packages in order to be able to export to other modules (or at least that's what I ended up with). So if another library is modularised, `RoaringBitmaps` can't be used easily and I had to merge `RoaringBitmap` and `shims` libraries using the "shade" plugin (see attached `pom.xml`):

[pom.zip](https://github.com/RoaringBitmap/RoaringBitmap/files/12680435/pom.zip)

So I'd at least suggest:

a) dropping `shims` module and integrate it directly into `RoaringBitmaps` module
b) moving `ArraysShim` from `org.roaringbitmap` package to separate one - fe. `org.roaringbitmap.shims`

Both proposals would allot to use RoaringBitmaps from modularised projects as automatic modules.

**Comment by novoj** [comment] 2023-09-21 06:02
> Added a PR here which adds `module-info.java` without dropping Java 8 support: #657

Will it work? If you exclude `module-info.java` from the build, will it be present and compiled in the target JAR? I have attached a screenshot of what the internal structure of the modularised JAR looks like:

![image](https://github.com/RoaringBitmap/RoaringBitmap/assets/202912/187be27e-e32f-40fa-9c18-cbbb622024bb)

**Comment by lemire** [comment] 2023-09-21 12:18
@novoj 

> will it be present and compiled in the target JAR?

It appears to be, when I build it. Have you checked inside the jar produced by the pull request, or are your concerns theoretical?

**Comment by novoj** [comment] 2023-09-21 12:39
I tried it, but in wrong branch. I confirm that in branch `ticket-651-add-java-modules-support` the `module-java.class` is present.

**Closed** 2023-09-22 13:15 UTC
Labels: enhancement

**Comment by lemire** [comment] 2023-09-22 13:19
@matteo-catena Please see https://github.com/RoaringBitmap/RoaringBitmap/releases/tag/1.0.0
