### ISSUE TITLE
BufferParallelAggregation throws due to faulty partitioning function

### ISSUE THREAD

**Issue by ppiotrow** [RoaringBitmap/RoaringBitmap#309] opened 2019-02-19 08:06 UTC
I've migrated our bitmap execution software from VM with 8 cores to cloud where I enabled cpu shares corresponding to 32 cores according to `Runtime.getRuntime.availableProcessors()`.
In the logs started appearing this error quite frequently (~1 per 10 requests fails).
I'm running on RoaringBitmap `0.7.21`

```
Caused by: java.lang.IllegalArgumentException: fromIndex(837) > toIndex(833)
	at java.util.ArrayList.subListRangeCheck(ArrayList.java:1014)
	at java.util.ArrayList.subList(ArrayList.java:1004)
	at org.roaringbitmap.buffer.BufferParallelAggregation.lambda$or$12(BufferParallelAggregation.java:229)
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721)
	at java.util.stream.AbstractTask.compute(AbstractTask.java:316)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1870)
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2045)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:404)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.roaringbitmap.buffer.BufferParallelAggregation.or(BufferParallelAggregation.java:231)
	at org.roaringbitmap.buffer.BufferParallelAggregation.lambda$or$11(BufferParallelAggregation.java:181)
	at java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:205)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
```

Estimated values for failing example are:
```
containers.size() = 833
parallelism = 32
partition_size = 27
List.tabulate(32)(i => (i * 27, Math.min((i + 1) * 27, 833)))
List((0,27), (27,54), (54,81), (81,108), (108,135), (135,162), (162,189), (189,216), (216,243), (243,270), (270,297), (297,324), (324,351), (351,378), (378,405), (405,432), (432,459), (459,486), (486,513), (513,540), (540,567), (567,594), (594,621), (621,648), (648,675), (675,702), (702,729), (729,756), (756,783), (783,810), (810,833), (837,833))
```
which reproduces a bug.

**Comment by ppiotrow** [comment] 2019-02-19 12:06
Not sure if the current code should be fixed or we need a new piece of code here.
I think the aim is to create as equally in size partitions as possible. 
I came up with following algorithm (not unit tested yet).
```scala
val limit = 833
val partitions = 32
val step = Math.floorDiv(limit, partitions)
val mod = Math.floorMod(limit, partitions)
List.tabulate(partitions) { i =>
  if (i < mod)
    (i * (step + 1), (i + 1) * (step + 1))
  else
    (mod + i * step, mod + (i + 1) * step)
}
```

**Comment by lemire** [comment] 2019-02-19 13:54
I have changed the label on this issue to "potential bug". As far as I can tell, we have no way of determining whether there is a bug in the RoaringBitmap library. From what I understand, you suspect that there might be a bug in `BufferParallelAggregation.or`... maybe something related to concurrency.

Having access to a beast with many cores is not too difficult. But we need an actual reproducible test. (Where "reproducible" might take a probabilistic sense here.)

Can you reduce your issue, using as little of your own code as possible? Ideally, the test case would setup the input data, call `BufferParallelAggregation.or` and then get the wrong answer, doing nothing else.

If other people cannot reproduce or see the issue, I don't think we can fairly label the issue as a bug. 

I don't understand the part about "equally in size partitions". 

Can you reduce the bug and discard anything non-essential from your own application?

**Comment by ppiotrow** [comment] 2019-02-19 14:26
The equation [here](https://github.com/RoaringBitmap/RoaringBitmap/blob/master/roaringbitmap/src/main/java/org/roaringbitmap/buffer/BufferParallelAggregation.java#L230) or [here](https://github.com/RoaringBitmap/RoaringBitmap/blob/master/roaringbitmap/src/main/java/org/roaringbitmap/ParallelAggregation.java#L223) is buggy and I proved it in the first snippet. It produces the array slices where left index is greater the right index. 
I've seen this equation several times in various places in the Internet and I wonder how come it has bug. Also is kind of strange that I was never affected on 8 core machines and I don't understand that.
I pushed a failing unit test which that is not minimal but just-failing example [here](https://github.com/RoaringBitmap/RoaringBitmap/pull/310).
Regarding equally sized partitions I assume we divide the array of containers to as equal in size subsets in order to optimise parallelisation of alternative.

**Comment by lemire** [comment] 2019-02-19 14:33
Now I understand. It is indeed a mathematical bug.

**Comment by lemire** [comment] 2019-02-19 14:36
Marked as a bug and changed title to something that better reflects the issue in my opinion.

**Comment by lemire** [comment] 2019-02-19 14:55
PR https://github.com/RoaringBitmap/RoaringBitmap/pull/310 fixed the issue.

**Closed by lemire** 2019-02-19 14:55 UTC
Labels: bug

**Comment by richardstartin** [comment] 2019-02-19 15:09
I’m amazed that this has seen enough use to earn a bug report!

**Comment by ppiotrow** [comment] 2019-02-20 09:12
@richardstartin Parallel aggregation is awesome :) 
@lemire do you plan to release version with fixes?

**Comment by lemire** [comment] 2019-02-20 13:56
A release was issued.
